<definitions name="sign-policy" 
	xmlns="http://schemas.xmlsoap.org/wsdl/" 
	xmlns:wsp="http://www.w3.org/ns/ws-policy"
	xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"
	xmlns:sp="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702">

	<wsp:Policy wsu:Id="Sign">
		<wsp:ExactlyOne>
			<wsp:All>

				<sp:AsymmetricBinding>
					<wsp:Policy>

						<sp:InitiatorToken>
							<wsp:Policy>
								<sp:X509Token sp:IncludeToken="http://docs.oasis-open.org/ws-sx/ws-securitypolicy/200702/IncludeToken/AlwaysToRecipient">
									<wsp:Policy>
										<sp:WssX509V3Token10 />
									</wsp:Policy>
								</sp:X509Token>
							</wsp:Policy>
						</sp:InitiatorToken>

						<sp:Layout>
							<wsp:Policy>
								<sp:Strict />
							</wsp:Policy>
						</sp:Layout>

						<sp:IncludeTimestamp />

						<sp:AlgorithmSuite>
							<wsp:Policy>
								<sp:Basic256Sha256 />
							</wsp:Policy>
						</sp:AlgorithmSuite>						

					</wsp:Policy>
				</sp:AsymmetricBinding>

				<sp:SignedParts>
					<sp:Body />
				</sp:SignedParts>

				<sp:Wss10 xmlns:sp="http://schemas.xmlsoap.org/ws/2005/07/securitypolicy">
					<wsp:Policy>
						<sp:MustSupportRefKeyIdentifier />
					</wsp:Policy>
				</sp:Wss10>
							
			</wsp:All>
		</wsp:ExactlyOne>
	</wsp:Policy>
</definitions>
